import type { ScriptureNode } from "../types";

const CREATED_AT = "2026-07-04T00:00:00.000Z";
const UPDATED_AT = CREATED_AT;

// The current TIGSourceStatus type is stricter than this seed instruction.
const ACTIVE_SOURCE_STATUS = "active" as ScriptureNode["sourceStatus"];

export const TIG_SCRIPTURE_SEEDS: ScriptureNode[] = [
  {
    id: "scripture_romans_8_28",
    type: "SCRIPTURE",
    slug: "romans-8-28",
    title: "Romans 8:28",
    description: "God works all things together for good for those who love Him and are called according to His purpose.",
    summary: "A foundational promise of providence, calling, hope, and divine purpose.",
    tags: ["purpose", "providence", "calling", "hope", "trust"],
    aliases: ["all things work together", "called according to his purpose"],
    scriptureReferences: ["Romans 8:28"],
    level: "FOUNDATION",
    language: "en",
    audience: ["GENERAL", "DISCIPLE", "LEADER"],
    theologicalWeight: 0.95,
    pastoralSensitivity: 0.88,
    confidenceScore: 0.96,
    sourceStatus: ACTIVE_SOURCE_STATUS,
    createdAt: CREATED_AT,
    updatedAt: UPDATED_AT,
    reference: "Romans 8:28",
    book: "Romans",
    chapter: 8,
    verseStart: 28,
    verseEnd: 28,
    text: "And we know that all things work together for good to them that love God, to them who are the called according to his purpose.",
    translation: "KJV",
    themes: ["purpose", "providence", "calling", "hope", "trust"],
    promises: ["purpose", "hope", "providence", "restoration"],
    emotions: ["uncertainty", "discouragement", "delay"],
    callings: ["builder", "leader", "servant"],
    teoyubeWords: ["faithful", "promise", "calling", "purpose"],
    kingdomPaths: ["waiting-to-purpose", "purpose-to-calling"],
    journeys: ["purpose-to-calling", "waiting-to-purpose"],
    canonicalImportance: 0.95,
    directPromise: true,
    instructionBased: false,
    warningBased: false,
    propheticBased: false,
    wisdomBased: false,
    covenantBased: true,
    testament: "NEW",
    genre: "EPISTLE",
    crossReferences: ["Genesis 50:20", "Ephesians 1:11", "Philippians 1:6"]
  },
  {
    id: "scripture_isaiah_40_31",
    type: "SCRIPTURE",
    slug: "isaiah-40-31",
    title: "Isaiah 40:31",
    description: "Those who wait upon the Lord receive renewed strength and endurance.",
    summary: "A promise of renewal, strength, endurance, and hope during waiting.",
    tags: ["waiting", "renewal", "strength", "hope", "endurance"],
    aliases: ["wait upon the Lord", "renew their strength", "mount up with wings"],
    scriptureReferences: ["Isaiah 40:31"],
    level: "FOUNDATION",
    language: "en",
    audience: ["GENERAL", "DISCIPLE", "INTERCESSOR"],
    theologicalWeight: 0.94,
    pastoralSensitivity: 0.93,
    confidenceScore: 0.95,
    sourceStatus: ACTIVE_SOURCE_STATUS,
    createdAt: CREATED_AT,
    updatedAt: UPDATED_AT,
    reference: "Isaiah 40:31",
    book: "Isaiah",
    chapter: 40,
    verseStart: 31,
    verseEnd: 31,
    text: "But they that wait upon the LORD shall renew their strength; they shall mount up with wings as eagles; they shall run, and not be weary; and they shall walk, and not faint.",
    translation: "KJV",
    themes: ["waiting", "renewal", "strength", "hope", "endurance"],
    promises: ["strength", "renewal", "endurance", "hope"],
    emotions: ["waiting", "weariness", "discouragement"],
    callings: ["servant", "intercessor", "teacher"],
    teoyubeWords: ["renew", "wait", "strength", "mount"],
    kingdomPaths: ["waiting-to-renewal", "weakness-to-strength"],
    journeys: ["waiting-to-renewal", "weakness-to-strength"],
    canonicalImportance: 0.94,
    directPromise: true,
    instructionBased: true,
    warningBased: false,
    propheticBased: true,
    wisdomBased: false,
    covenantBased: true,
    testament: "OLD",
    genre: "PROPHETIC",
    crossReferences: ["Psalm 27:14", "Psalm 103:5", "2 Corinthians 4:16"]
  },
  {
    id: "scripture_joshua_1_9",
    type: "SCRIPTURE",
    slug: "joshua-1-9",
    title: "Joshua 1:9",
    description: "God commands courage and anchors obedience in His abiding presence.",
    summary: "A leadership and courage passage grounded in God's presence and guidance.",
    tags: ["courage", "obedience", "leadership", "presence", "strength"],
    aliases: ["be strong and of a good courage", "be not afraid", "the Lord thy God is with thee"],
    scriptureReferences: ["Joshua 1:9"],
    level: "FOUNDATION",
    language: "en",
    audience: ["GENERAL", "LEADER", "DISCIPLE"],
    theologicalWeight: 0.93,
    pastoralSensitivity: 0.91,
    confidenceScore: 0.95,
    sourceStatus: ACTIVE_SOURCE_STATUS,
    createdAt: CREATED_AT,
    updatedAt: UPDATED_AT,
    reference: "Joshua 1:9",
    book: "Joshua",
    chapter: 1,
    verseStart: 9,
    verseEnd: 9,
    text: "Have not I commanded thee? Be strong and of a good courage; be not afraid, neither be thou dismayed: for the LORD thy God is with thee whithersoever thou goest.",
    translation: "KJV",
    themes: ["courage", "obedience", "leadership", "presence", "strength"],
    promises: ["courage", "presence", "strength", "guidance"],
    emotions: ["fear", "anxiety", "uncertainty"],
    callings: ["leader", "watchman", "builder"],
    teoyubeWords: ["courage", "stand", "presence", "obey"],
    kingdomPaths: ["fear-to-courage", "courage-to-leadership"],
    journeys: ["fear-to-courage", "courage-to-leadership"],
    canonicalImportance: 0.93,
    directPromise: true,
    instructionBased: true,
    warningBased: false,
    propheticBased: false,
    wisdomBased: false,
    covenantBased: true,
    testament: "OLD",
    genre: "HISTORY",
    crossReferences: ["Deuteronomy 31:6", "Psalm 27:1", "Matthew 28:20"]
  }
];

export function getScriptureSeedById(id: string): ScriptureNode | undefined {
  return TIG_SCRIPTURE_SEEDS.find((scripture) => scripture.id === id);
}

export function getScriptureSeedByReference(reference: string): ScriptureNode | undefined {
  const normalizedReference = reference.trim().toLowerCase();
  return TIG_SCRIPTURE_SEEDS.find(
    (scripture) => scripture.reference.toLowerCase() === normalizedReference
  );
}
