import type { TeoyubeControlledPublicCommunicationStatus, TeoyubeControlledPublicLaunchActivationBlocker, TeoyubeControlledPublicLaunchActivationCheck, TeoyubeControlledPublicLaunchActivationWarning } from "./controlled-public-launch-activation-contracts";
const phase = "public_communication_readiness" as const;
function item(id: string, label: string): TeoyubeControlledPublicLaunchActivationCheck { return { id, label, phase, required: true, complete: true, launchCritical: true, details: label }; }
function block(id: string, reason: string): TeoyubeControlledPublicLaunchActivationBlocker { return { id, label: id.replace(/_/g, " "), phase, severity: "critical", reason, requiredAction: "Fix public communication readiness before manual public activation." }; }
export function getControlledPublicCommunicationChecklist(): TeoyubeControlledPublicLaunchActivationCheck[] { return [
  item("public_launch_notice_draft_exists", "Public launch notice draft exists"), item("privacy_notice_available", "Privacy notice is available"), item("terms_notice_available", "Terms notice is available"), item("consent_notice_available", "Consent notice is available"), item("sensitive_information_warning_exists", "Sensitive information warning exists"), item("ai_tig_transparency_notice_exists", "AI/TIG transparency notice exists"), item("known_limitations_notice_exists", "Public known limitations notice exists"), item("feedback_instructions_exist", "Feedback instructions exist"), item("no_messages_sent_by_code", "No messages are sent by code"), item("no_sensitive_personal_information_instruction", "Users are told not to submit sensitive personal information"), item("no_divine_certainty_claim", "Users are told Teoyube does not claim divine certainty"), item("professional_advice_boundary", "Users are told Teoyube is not professional advice"), item("personalization_consent_notice", "Users are told how personalization and consent work"), item("production_service_status_notice", "Users are told which production services are active or deferred")
]; }
export function createControlledPublicCommunicationReadinessPlan(input: Partial<TeoyubeControlledPublicCommunicationStatus> = {}): TeoyubeControlledPublicCommunicationStatus { return { id: input.id || "controlled_public_communication_6_1", label: input.label || "Controlled Public Communication Readiness", publicLaunchNoticeDraftExists: input.publicLaunchNoticeDraftExists ?? true, privacyNoticeAvailable: input.privacyNoticeAvailable ?? true, termsNoticeAvailable: input.termsNoticeAvailable ?? true, consentNoticeAvailable: input.consentNoticeAvailable ?? true, sensitiveInformationWarningExists: input.sensitiveInformationWarningExists ?? true, aiTigTransparencyNoticeExists: input.aiTigTransparencyNoticeExists ?? true, knownLimitationsNoticeExists: input.knownLimitationsNoticeExists ?? true, feedbackInstructionsExist: input.feedbackInstructionsExist ?? true, noDivineCertaintyClaimIncluded: input.noDivineCertaintyClaimIncluded ?? true, professionalAdviceBoundaryIncluded: input.professionalAdviceBoundaryIncluded ?? true, personalizationConsentNoticeIncluded: input.personalizationConsentNoticeIncluded ?? true, productionServiceStatusNoticeIncluded: input.productionServiceStatusNoticeIncluded ?? true, messagesSentByCode: false, usersContacted: false, generatedAt: input.generatedAt || new Date().toISOString() }; }
export function getControlledPublicCommunicationBlockers(plan: TeoyubeControlledPublicCommunicationStatus): TeoyubeControlledPublicLaunchActivationBlocker[] { return [
  !plan.publicLaunchNoticeDraftExists ? block("controlled_public_notice_missing", "Public launch notice draft must exist.") : undefined,
  !plan.privacyNoticeAvailable ? block("controlled_public_privacy_notice_missing", "Privacy notice must be available.") : undefined,
  !plan.termsNoticeAvailable ? block("controlled_public_terms_notice_missing", "Terms notice must be available.") : undefined,
  !plan.consentNoticeAvailable ? block("controlled_public_consent_notice_missing", "Consent notice must be available.") : undefined,
  !plan.sensitiveInformationWarningExists ? block("controlled_public_sensitive_warning_missing", "Sensitive information warning must exist.") : undefined,
  !plan.aiTigTransparencyNoticeExists ? block("controlled_public_ai_tig_notice_missing", "AI/TIG transparency notice must exist.") : undefined,
  !plan.knownLimitationsNoticeExists ? block("controlled_public_limitations_notice_missing", "Known limitations notice must exist.") : undefined,
  !plan.feedbackInstructionsExist ? block("controlled_public_feedback_instructions_missing", "Feedback instructions must exist.") : undefined,
  !plan.noDivineCertaintyClaimIncluded ? block("controlled_public_divine_certainty_boundary_missing", "Communication must state Teoyube does not claim divine certainty.") : undefined,
  !plan.professionalAdviceBoundaryIncluded ? block("controlled_public_professional_boundary_missing", "Communication must state professional-advice boundaries.") : undefined,
  !plan.personalizationConsentNoticeIncluded ? block("controlled_public_personalization_notice_missing", "Communication must explain personalization and consent.") : undefined,
  !plan.productionServiceStatusNoticeIncluded ? block("controlled_public_service_status_notice_missing", "Communication must explain active or deferred production services.") : undefined,
  plan.messagesSentByCode ? block("controlled_public_messages_sent_by_code", "Code must not send communications.") : undefined,
  plan.usersContacted ? block("controlled_public_users_contacted", "Communication readiness must not contact users.") : undefined
].filter(Boolean) as TeoyubeControlledPublicLaunchActivationBlocker[]; }
export function getControlledPublicCommunicationWarnings(): TeoyubeControlledPublicLaunchActivationWarning[] { return [{ id: "controlled_public_communication_draft_only", label: "Communication is draft only", phase, severity: "medium", message: "Communication readiness prepares public notices but sends nothing.", recommendedAction: "Send any public messages manually outside code after owner approval." }]; }
export function validateControlledPublicCommunicationReadiness(plan: TeoyubeControlledPublicCommunicationStatus) { const blockers = getControlledPublicCommunicationBlockers(plan); return { valid: blockers.length === 0, blockers, warnings: getControlledPublicCommunicationWarnings() }; }
export function createControlledPublicCommunicationReadinessReport(plan: TeoyubeControlledPublicCommunicationStatus = createControlledPublicCommunicationReadinessPlan()) { const validation = validateControlledPublicCommunicationReadiness(plan); return { valid: validation.valid, ready: validation.valid, plan, blockers: validation.blockers, warnings: validation.warnings, noMessagesSent: true, noUsersContacted: true, noExternalWrite: true, generatedAt: new Date().toISOString() }; }
