import type { TeoyubeControlledPublicLaunchActivationBlocker, TeoyubeControlledPublicLaunchActivationCheck, TeoyubeControlledPublicLaunchActivationWarning } from "./controlled-public-launch-activation-contracts";
export type TeoyubeControlledPublicFirstHourReadinessPlan={id:string;label:string;checklist:TeoyubeControlledPublicLaunchActivationCheck[];fetchesPublicUrls:false;monitoringPerformed:false;generatedAt:string;};
const phase="first_hour_monitoring_readiness" as const;
function item(id:string,label:string):TeoyubeControlledPublicLaunchActivationCheck{return{id,label,phase,required:true,complete:true,launchCritical:true,details:label};}
function block(entry:TeoyubeControlledPublicLaunchActivationCheck):TeoyubeControlledPublicLaunchActivationBlocker{return{id:"controlled_public_first_hour_"+entry.id,label:entry.label,phase,severity:"critical",reason:entry.details,requiredAction:"Prepare this manual first-hour public monitoring check before activation."};}
export function getControlledPublicFirstHourChecklist():TeoyubeControlledPublicLaunchActivationCheck[]{return ["public_app_loads_manual:Verify public app loads manually","public_home_manual:Verify public home manually, if present","canon_manual:Verify Canon manually","daily_word_manual:Verify Daily Word manually","prayer_manual:Verify Prayer manually","calling_compass_manual:Verify Calling Compass manually","promise_cluster_manual:Verify Promise Cluster manually","ai_companion_manual:Verify AI Companion manually","onboarding_manual:Verify Onboarding manually","privacy_page_manual:Verify Privacy page manually","terms_page_manual:Verify Terms page manually","consent_page_manual:Verify Consent page manually","scripture_anchors_manual:Verify Scripture anchors","explanation_paths_manual:Verify explanation paths","fallback_behavior_manual:Verify fallback behavior","consent_controls_manual:Verify consent controls","public_copy_visibility_manual:Verify public copy visibility","mobile_layout_manual:Verify mobile layout","no_debug_payload_exposed:Verify no debug payload exposed","no_unapproved_external_analytics:Verify no unapproved external analytics","no_unapproved_production_persistence:Verify no unapproved production persistence","no_unapproved_live_ai_orchestration:Verify no unapproved live AI orchestration"].map((entry)=>{const [id,...label]=entry.split(":");return item(id,label.join(":"));});}
export function createControlledPublicFirstHourReadinessPlan(input:Partial<TeoyubeControlledPublicFirstHourReadinessPlan>={}):TeoyubeControlledPublicFirstHourReadinessPlan{return{id:input.id||"controlled_public_first_hour_6_1",label:input.label||"First-Hour Public Monitoring Readiness Plan",checklist:input.checklist||getControlledPublicFirstHourChecklist(),fetchesPublicUrls:false,monitoringPerformed:false,generatedAt:input.generatedAt||new Date().toISOString()};}
export function getControlledPublicFirstHourBlockers(plan:TeoyubeControlledPublicFirstHourReadinessPlan):TeoyubeControlledPublicLaunchActivationBlocker[]{return[...plan.checklist.filter((entry)=>entry.required&&!entry.complete).map(block),plan.fetchesPublicUrls?{id:"controlled_public_first_hour_public_url_fetched",label:"Public URL fetched",phase,severity:"critical",reason:"First-hour readiness must not fetch public URLs.",requiredAction:"Keep URL checks manual."}:undefined,plan.monitoringPerformed?{id:"controlled_public_first_hour_monitoring_performed",label:"Monitoring performed",phase,severity:"critical",reason:"This module must not perform monitoring automatically.",requiredAction:"Use this as a manual checklist only."}:undefined].filter(Boolean) as TeoyubeControlledPublicLaunchActivationBlocker[];}
export function getControlledPublicFirstHourWarnings():TeoyubeControlledPublicLaunchActivationWarning[]{return[{id:"controlled_public_first_hour_manual_only",label:"First-hour public monitoring is manual only",phase,severity:"medium",message:"This plan prepares checks but does not fetch URLs or observe live users.",recommendedAction:"Run checks manually during the approved public launch window."}];}
export function validateControlledPublicFirstHourReadiness(plan:TeoyubeControlledPublicFirstHourReadinessPlan){const blockers=getControlledPublicFirstHourBlockers(plan);return{valid:blockers.length===0,blockers,warnings:getControlledPublicFirstHourWarnings()};}
export function createControlledPublicFirstHourReadinessReport(plan:TeoyubeControlledPublicFirstHourReadinessPlan=createControlledPublicFirstHourReadinessPlan()){const validation=validateControlledPublicFirstHourReadiness(plan);return{valid:validation.valid,ready:validation.valid,plan,checklistCount:plan.checklist.length,blockers:validation.blockers,warnings:validation.warnings,noMonitoringPerformed:true,noPublicUrlFetched:true,generatedAt:new Date().toISOString()};}
