import type { TeoyubeControlledPublicLaunchActivationBlocker, TeoyubeControlledPublicLaunchActivationWarning, TeoyubeControlledPublicPauseRollbackStatus } from "./controlled-public-launch-activation-contracts";
const phase="pause_rollback_readiness" as const;
export function getControlledPublicPauseCriteria():string[]{return["Public app does not load","Privacy, terms, or consent notices missing","Scripture anchors missing","Explanation paths missing","Unsafe fallback behavior","Consent controls missing","Debug payload exposed","Critical mobile blocker","Critical accessibility blocker","Privacy concern","Accidental analytics sending","Accidental persistence enablement","Accidental live AI orchestration","Confusing or unsafe spiritual guidance"];}
export function getControlledPublicRollbackCriteria():string[]{return getControlledPublicPauseCriteria().map((entry)=>entry+" remains unresolved after owner review");}
function block(id:string,reason:string):TeoyubeControlledPublicLaunchActivationBlocker{return{id,label:id.replace(/_/g," "),phase,severity:"critical",reason,requiredAction:"Fix public pause/rollback readiness before manual public activation."};}
export function createControlledPublicPauseRollbackPlan(input:Partial<TeoyubeControlledPublicPauseRollbackStatus>={}):TeoyubeControlledPublicPauseRollbackStatus{return{id:input.id||"controlled_public_pause_rollback_6_1",label:input.label||"Controlled Public Pause and Rollback Readiness",pauseCriteria:input.pauseCriteria||getControlledPublicPauseCriteria(),rollbackCriteria:input.rollbackCriteria||getControlledPublicRollbackCriteria(),rollbackPerformed:false,providerCommandsExecuted:false,manualDecisionOnly:true,generatedAt:input.generatedAt||new Date().toISOString()};}
export function getControlledPublicPauseRollbackBlockers(plan:TeoyubeControlledPublicPauseRollbackStatus):TeoyubeControlledPublicLaunchActivationBlocker[]{return[plan.pauseCriteria.length===0?block("controlled_public_pause_criteria_missing","Pause criteria must exist."):undefined,plan.rollbackCriteria.length===0?block("controlled_public_rollback_criteria_missing","Rollback criteria must exist."):undefined,plan.rollbackPerformed?block("controlled_public_rollback_performed","This module must not perform rollback."):undefined,plan.providerCommandsExecuted?block("controlled_public_provider_commands_executed","This module must not execute provider commands."):undefined].filter(Boolean) as TeoyubeControlledPublicLaunchActivationBlocker[];}
export function getControlledPublicPauseRollbackWarnings():TeoyubeControlledPublicLaunchActivationWarning[]{return[{id:"controlled_public_pause_rollback_manual_only",label:"Pause/rollback is manual only",phase,severity:"medium",message:"Readiness criteria exist, but no rollback is performed by code.",recommendedAction:"Owner should make pause or rollback decisions manually."}];}
export function validateControlledPublicPauseRollbackReadiness(plan:TeoyubeControlledPublicPauseRollbackStatus){const blockers=getControlledPublicPauseRollbackBlockers(plan);return{valid:blockers.length===0,blockers,warnings:getControlledPublicPauseRollbackWarnings()};}
export function createControlledPublicPauseRollbackReport(plan:TeoyubeControlledPublicPauseRollbackStatus=createControlledPublicPauseRollbackPlan()){const validation=validateControlledPublicPauseRollbackReadiness(plan);return{valid:validation.valid,ready:validation.valid,plan,pauseCriteria:plan.pauseCriteria,rollbackCriteria:plan.rollbackCriteria,blockers:validation.blockers,warnings:validation.warnings,noRollbackPerformed:true,noProviderCommandsExecuted:true,generatedAt:new Date().toISOString()};}
