import type { TeoyubeControlledPublicLaunchActivationBlocker, TeoyubeControlledPublicLaunchActivationCheck, TeoyubeControlledPublicLaunchActivationWarning } from "./controlled-public-launch-activation-contracts";
import { createFinalProductionServiceDecisionReport } from "./final-production-service-decision";
export type TeoyubeControlledPublicServiceState = "approved_active" | "approved_disabled" | "disabled" | "deferred" | "unknown";
export type TeoyubeControlledPublicServiceStatusInput = { databaseStatus?: TeoyubeControlledPublicServiceState; analyticsStatus?: TeoyubeControlledPublicServiceState; liveAiStatus?: TeoyubeControlledPublicServiceState; monitoringStatus?: TeoyubeControlledPublicServiceState; emailNotificationStatus?: TeoyubeControlledPublicServiceState; storageStatus?: TeoyubeControlledPublicServiceState; authenticationStatus?: TeoyubeControlledPublicServiceState; searchStatus?: TeoyubeControlledPublicServiceState; disabledServiceAccidentallyActive?: boolean; publicCopyConflictsWithServiceStatus?: boolean; deterministicTigEnabled?: boolean; externalServicesCalled?: boolean; };
const phase = "production_service_confirmation" as const;
function item(id: string, label: string): TeoyubeControlledPublicLaunchActivationCheck { return { id, label, phase, required: true, complete: true, launchCritical: true, details: label }; }
function block(id: string, reason: string): TeoyubeControlledPublicLaunchActivationBlocker { return { id, label: id.replace(/_/g, " "), phase, severity: "critical", reason, requiredAction: "Resolve public production service status before manual public activation." }; }
function known(status: TeoyubeControlledPublicServiceState | undefined): boolean { return Boolean(status && status !== "unknown"); }
function approvedOrDisabled(status: TeoyubeControlledPublicServiceState | undefined): boolean { return status === "approved_active" || status === "approved_disabled" || status === "disabled" || status === "deferred"; }
function withDefaults(input: TeoyubeControlledPublicServiceStatusInput = {}): Required<TeoyubeControlledPublicServiceStatusInput> { return { databaseStatus: input.databaseStatus || "disabled", analyticsStatus: input.analyticsStatus || "disabled", liveAiStatus: input.liveAiStatus || "disabled", monitoringStatus: input.monitoringStatus || "deferred", emailNotificationStatus: input.emailNotificationStatus || "deferred", storageStatus: input.storageStatus || "deferred", authenticationStatus: input.authenticationStatus || "deferred", searchStatus: input.searchStatus || "deferred", disabledServiceAccidentallyActive: input.disabledServiceAccidentallyActive ?? false, publicCopyConflictsWithServiceStatus: input.publicCopyConflictsWithServiceStatus ?? false, deterministicTigEnabled: input.deterministicTigEnabled ?? true, externalServicesCalled: input.externalServicesCalled ?? false }; }
export function getControlledPublicServiceStatusChecklist(): TeoyubeControlledPublicLaunchActivationCheck[] { return [item("database_status_known", "Database persistence status is known and approved or disabled"), item("analytics_status_known", "Analytics status is known and approved or disabled"), item("live_ai_status_known", "Live AI orchestration status is known and approved or disabled"), item("monitoring_status_known", "Monitoring status is known and approved or disabled"), item("email_notification_status_known", "Email/notification status is known and approved or disabled"), item("storage_auth_search_status_known", "Storage, auth, and search status is known if applicable"), item("no_disabled_service_accidentally_active", "No disabled service is accidentally active"), item("no_public_copy_service_conflict", "No service claim in public copy conflicts with actual status"), item("deterministic_tig_safe_default", "Deterministic TIG production layer remains the safe default")]; }
export function getControlledPublicServiceStatusBlockers(input: TeoyubeControlledPublicServiceStatusInput = {}): TeoyubeControlledPublicLaunchActivationBlocker[] { const status = withDefaults(input); return [
  !known(status.databaseStatus) || !approvedOrDisabled(status.databaseStatus) ? block("controlled_public_database_status_unknown", "Database persistence status must be known and approved or disabled.") : undefined,
  !known(status.analyticsStatus) || !approvedOrDisabled(status.analyticsStatus) ? block("controlled_public_analytics_status_unknown", "Analytics status must be known and approved or disabled.") : undefined,
  !known(status.liveAiStatus) || !approvedOrDisabled(status.liveAiStatus) ? block("controlled_public_live_ai_status_unknown", "Live AI orchestration status must be known and approved or disabled.") : undefined,
  !known(status.monitoringStatus) || !approvedOrDisabled(status.monitoringStatus) ? block("controlled_public_monitoring_status_unknown", "Monitoring status must be known and approved or disabled.") : undefined,
  !known(status.emailNotificationStatus) || !approvedOrDisabled(status.emailNotificationStatus) ? block("controlled_public_email_status_unknown", "Email/notification status must be known and approved or disabled.") : undefined,
  !known(status.storageStatus) || !known(status.authenticationStatus) || !known(status.searchStatus) ? block("controlled_public_storage_auth_search_status_unknown", "Storage, auth, and search status must be known if applicable.") : undefined,
  status.disabledServiceAccidentallyActive ? block("controlled_public_disabled_service_active", "A disabled service is accidentally active.") : undefined,
  status.publicCopyConflictsWithServiceStatus ? block("controlled_public_service_copy_conflict", "A public copy service claim conflicts with actual service status.") : undefined,
  !status.deterministicTigEnabled ? block("controlled_public_deterministic_tig_disabled", "Deterministic TIG must remain the safe default when live AI is disabled.") : undefined,
  status.externalServicesCalled ? block("controlled_public_service_external_call", "Service status confirmation must not call external services.") : undefined
].filter(Boolean) as TeoyubeControlledPublicLaunchActivationBlocker[]; }
export function getControlledPublicServiceStatusWarnings(input: TeoyubeControlledPublicServiceStatusInput = {}): TeoyubeControlledPublicLaunchActivationWarning[] { const status = withDefaults(input); const finalServices = createFinalProductionServiceDecisionReport(); return [{ id: "controlled_public_services_manual_confirmation", label: "Services require manual confirmation", phase, severity: "medium", message: "Database=" + status.databaseStatus + "; analytics=" + status.analyticsStatus + "; live AI=" + status.liveAiStatus + ".", recommendedAction: "Owner should compare public copy with actual provider configuration before manual activation." }, finalServices.ready ? undefined : { id: "controlled_public_final_service_decision_review", label: "Final service decision review needed", phase, severity: "high", message: "Final production service decision report is not ready.", recommendedAction: "Resolve final production service decision blockers before public activation." }].filter(Boolean) as TeoyubeControlledPublicLaunchActivationWarning[]; }
export function validateControlledPublicServiceStatus(input: TeoyubeControlledPublicServiceStatusInput = {}) { const blockers = getControlledPublicServiceStatusBlockers(input); return { valid: blockers.length === 0, blockers, warnings: getControlledPublicServiceStatusWarnings(input) }; }
export function createControlledPublicServiceStatusReport(input: TeoyubeControlledPublicServiceStatusInput = {}) { const status = withDefaults(input); const validation = validateControlledPublicServiceStatus(status); return { valid: validation.valid, ready: validation.valid, checklist: getControlledPublicServiceStatusChecklist(), status, finalServiceDecision: createFinalProductionServiceDecisionReport(), blockers: validation.blockers, warnings: validation.warnings, noDisabledServiceAccidentallyActive: !status.disabledServiceAccidentallyActive, noPublicCopyServiceConflict: !status.publicCopyConflictsWithServiceStatus, deterministicTigSafeDefault: status.deterministicTigEnabled, noExternalServicesCalled: !status.externalServicesCalled, noExternalWrite: true, generatedAt: new Date().toISOString() }; }
