import { createControlledPublicLaunchActivationDecision, createControlledPublicLaunchActivationReport } from "./controlled-public-launch-activation-checklist";
import { createControlledPublicAccessReadinessPlan, createControlledPublicAccessReadinessReport } from "./controlled-public-access-readiness";
import { createControlledPublicCommunicationReadinessPlan, createControlledPublicCommunicationReadinessReport } from "./controlled-public-communication-readiness";
import { createControlledPublicFirstHourReadinessPlan, createControlledPublicFirstHourReadinessReport } from "./controlled-public-first-hour-readiness";
import { createControlledPublicIssueIntakePlan, createControlledPublicIssueIntakeReport } from "./controlled-public-issue-intake-readiness";
import { createControlledPublicOwnerApprovalRecord, createControlledPublicOwnerApprovalReport } from "./controlled-public-owner-approval";
import { createControlledPublicPauseRollbackPlan, createControlledPublicPauseRollbackReport } from "./controlled-public-pause-rollback-readiness";
import { createControlledPublicServiceStatusReport } from "./controlled-public-service-status-confirmation";
import { createControlledPublicLaunchWindowPlan, createControlledPublicLaunchWindowReport } from "./controlled-public-launch-window";
import { createFinalPublicLaunchPackage } from "./final-public-launch-package";
import type { TeoyubeControlledPublicLaunchActivationBlocker, TeoyubeControlledPublicLaunchActivationWarning } from "./controlled-public-launch-activation-contracts";
export type TeoyubeControlledPublicActivationPackage={id:string;label:string;activationChecklistReport:ReturnType<typeof createControlledPublicLaunchActivationReport>;ownerApprovalReport:ReturnType<typeof createControlledPublicOwnerApprovalReport>;launchWindowReport:ReturnType<typeof createControlledPublicLaunchWindowReport>;publicAccessReadinessReport:ReturnType<typeof createControlledPublicAccessReadinessReport>;communicationReadinessReport:ReturnType<typeof createControlledPublicCommunicationReadinessReport>;productionServiceStatusReport:ReturnType<typeof createControlledPublicServiceStatusReport>;firstHourReadinessReport:ReturnType<typeof createControlledPublicFirstHourReadinessReport>;issueIntakeReadinessReport:ReturnType<typeof createControlledPublicIssueIntakeReport>;pauseRollbackReadinessReport:ReturnType<typeof createControlledPublicPauseRollbackReport>;finalPublicLaunchPackageReference:string;knownLimitations:string[];nextAction:string;inMemoryOnly:true;sentExternally:false;fileWritten:false;databaseWritten:false;analyticsSent:false;publicLaunchPerformed:false;usersContacted:false;feedbackCollectedAutomatically:false;publicUrlFetched:false;externalServicesCalled:false;generatedAt:string;};
export type TeoyubeControlledPublicActivationPackageInput=Partial<Pick<TeoyubeControlledPublicActivationPackage,"knownLimitations"|"nextAction">>;
function block(id:string,reason:string):TeoyubeControlledPublicLaunchActivationBlocker{return{id,label:id.replace(/_/g," "),phase:"activation_decision",severity:"critical",reason,requiredAction:"Resolve this controlled public activation package blocker before manual activation."};}
export function createControlledPublicActivationPackage(input:TeoyubeControlledPublicActivationPackageInput={}):TeoyubeControlledPublicActivationPackage{const finalPackage=createFinalPublicLaunchPackage();return{id:"controlled_public_activation_package_6_1",label:"Public Launch Execution 6.1 Controlled Public Activation Package",activationChecklistReport:createControlledPublicLaunchActivationReport(),ownerApprovalReport:createControlledPublicOwnerApprovalReport(createControlledPublicOwnerApprovalRecord()),launchWindowReport:createControlledPublicLaunchWindowReport(createControlledPublicLaunchWindowPlan()),publicAccessReadinessReport:createControlledPublicAccessReadinessReport(createControlledPublicAccessReadinessPlan()),communicationReadinessReport:createControlledPublicCommunicationReadinessReport(createControlledPublicCommunicationReadinessPlan()),productionServiceStatusReport:createControlledPublicServiceStatusReport(),firstHourReadinessReport:createControlledPublicFirstHourReadinessReport(createControlledPublicFirstHourReadinessPlan()),issueIntakeReadinessReport:createControlledPublicIssueIntakeReport(createControlledPublicIssueIntakePlan()),pauseRollbackReadinessReport:createControlledPublicPauseRollbackReport(createControlledPublicPauseRollbackPlan()),finalPublicLaunchPackageReference:finalPackage.id,knownLimitations:input.knownLimitations||["Manual owner approval remains required before public activation.","Public users must not submit sensitive personal information.","External analytics, production persistence, and live AI orchestration remain disabled unless separately approved."],nextAction:input.nextAction||"Public Launch Execution 6.2 - Public Launch Day Monitoring & Feedback Intake",inMemoryOnly:true,sentExternally:false,fileWritten:false,databaseWritten:false,analyticsSent:false,publicLaunchPerformed:false,usersContacted:false,feedbackCollectedAutomatically:false,publicUrlFetched:false,externalServicesCalled:false,generatedAt:new Date().toISOString()};}
export function getControlledPublicActivationPackageBlockers(pkg:TeoyubeControlledPublicActivationPackage):TeoyubeControlledPublicLaunchActivationBlocker[]{return[...pkg.activationChecklistReport.blockers,...pkg.ownerApprovalReport.blockers,...pkg.launchWindowReport.blockers,...pkg.publicAccessReadinessReport.blockers,...pkg.communicationReadinessReport.blockers,...pkg.productionServiceStatusReport.blockers,...pkg.firstHourReadinessReport.blockers,...pkg.issueIntakeReadinessReport.blockers,...pkg.pauseRollbackReadinessReport.blockers,pkg.sentExternally?block("controlled_public_package_sent_externally","Activation package must not be sent externally."):undefined,pkg.fileWritten?block("controlled_public_package_file_written","Activation package must not write files."):undefined,pkg.databaseWritten?block("controlled_public_package_database_written","Activation package must not write databases."):undefined,pkg.analyticsSent?block("controlled_public_package_analytics_sent","Activation package must not send analytics."):undefined,pkg.publicLaunchPerformed?block("controlled_public_package_launched","Activation package must not perform public launch."):undefined,pkg.usersContacted?block("controlled_public_package_users_contacted","Activation package must not contact users."):undefined,pkg.feedbackCollectedAutomatically?block("controlled_public_package_feedback_collected","Activation package must not collect feedback automatically."):undefined,pkg.publicUrlFetched?block("controlled_public_package_public_url_fetched","Activation package must not fetch public URLs."):undefined,pkg.externalServicesCalled?block("controlled_public_package_external_services","Activation package must not call external services."):undefined].filter(Boolean) as TeoyubeControlledPublicLaunchActivationBlocker[];}
export function getControlledPublicActivationPackageWarnings(pkg:TeoyubeControlledPublicActivationPackage):TeoyubeControlledPublicLaunchActivationWarning[]{return[...pkg.activationChecklistReport.warnings,...pkg.ownerApprovalReport.warnings,...pkg.launchWindowReport.warnings,...pkg.publicAccessReadinessReport.warnings,...pkg.communicationReadinessReport.warnings,...pkg.productionServiceStatusReport.warnings,...pkg.firstHourReadinessReport.warnings,...pkg.issueIntakeReadinessReport.warnings,...pkg.pauseRollbackReadinessReport.warnings];}
export function createControlledPublicActivationPackageDecision(pkg:TeoyubeControlledPublicActivationPackage){return getControlledPublicActivationPackageBlockers(pkg).length===0?createControlledPublicLaunchActivationDecision():"blocked" as const;}
export function validateControlledPublicActivationPackage(pkg:TeoyubeControlledPublicActivationPackage){const blockers=getControlledPublicActivationPackageBlockers(pkg);return{valid:blockers.length===0,blockers,warnings:getControlledPublicActivationPackageWarnings(pkg)};}
export function createControlledPublicActivationPackageReport(pkg:TeoyubeControlledPublicActivationPackage=createControlledPublicActivationPackage()){const validation=validateControlledPublicActivationPackage(pkg);const decision=createControlledPublicActivationPackageDecision(pkg);return{valid:validation.valid,ready:validation.valid&&decision==="ready_for_manual_public_activation",decision,package:pkg,blockerCount:validation.blockers.length,warningCount:validation.warnings.length,blockers:validation.blockers,warnings:validation.warnings,inMemoryOnly:true,noPublicLaunchPerformed:true,noUsersContacted:true,noFeedbackCollectedAutomatically:true,noPublicUrlFetched:true,noExternalWrite:true,generatedAt:new Date().toISOString()};}
