import type { TeoyubeControlledPublicLaunchActivationBlocker, TeoyubeControlledPublicLaunchActivationCheck, TeoyubeControlledPublicLaunchActivationWarning } from "./controlled-public-launch-activation-contracts";
export type TeoyubeControlledPublicIssueIntakePlan={id:string;label:string;checklist:TeoyubeControlledPublicLaunchActivationCheck[];workflowMode:"manual"|"explicitly_controlled";feedbackCollectedAutomatically:false;issuesSentExternally:false;databaseWritten:false;generatedAt:string;};
const phase="public_feedback_intake_readiness" as const;
function item(id:string,label:string):TeoyubeControlledPublicLaunchActivationCheck{return{id,label,phase,required:true,complete:true,launchCritical:true,details:label};}
function block(entry:TeoyubeControlledPublicLaunchActivationCheck):TeoyubeControlledPublicLaunchActivationBlocker{return{id:"controlled_public_issue_intake_"+entry.id,label:entry.label,phase,severity:"critical",reason:entry.details,requiredAction:"Prepare this issue intake item before manual public activation."};}
export function getControlledPublicIssueIntakeChecklist():TeoyubeControlledPublicLaunchActivationCheck[]{return["public_issue_log_structure_exists:Public issue log structure exists","feedback_workflow_manual_or_controlled:Public feedback workflow is manual or explicitly controlled","public_issue_categories_exist:Public issue categories exist","privacy_issue_category_exists:Privacy issue category exists","scripture_anchor_issues_public_launch_critical:Scripture anchor issues are public-launch-critical","explanation_path_issues_public_launch_critical:Explanation path issues are public-launch-critical","fallback_issues_public_launch_critical:Fallback issues are public-launch-critical","consent_privacy_issues_public_launch_critical:Consent/privacy issues are public-launch-critical","mobile_accessibility_blockers_public_launch_critical:Mobile/accessibility blockers are public-launch-critical","no_feedback_collected_automatically:No feedback is collected automatically","no_issue_sent_externally:No issue is sent externally","no_database_writes:No database writes are made"].map((entry)=>{const [id,...label]=entry.split(":");return item(id,label.join(":"));});}
export function createControlledPublicIssueIntakePlan(input:Partial<TeoyubeControlledPublicIssueIntakePlan>={}):TeoyubeControlledPublicIssueIntakePlan{return{id:input.id||"controlled_public_issue_intake_6_1",label:input.label||"Controlled Public Issue Intake Readiness",checklist:input.checklist||getControlledPublicIssueIntakeChecklist(),workflowMode:input.workflowMode||"manual",feedbackCollectedAutomatically:false,issuesSentExternally:false,databaseWritten:false,generatedAt:input.generatedAt||new Date().toISOString()};}
export function getControlledPublicIssueIntakeBlockers(plan:TeoyubeControlledPublicIssueIntakePlan):TeoyubeControlledPublicLaunchActivationBlocker[]{return[...plan.checklist.filter((entry)=>entry.required&&!entry.complete).map(block),!["manual","explicitly_controlled"].includes(plan.workflowMode)?{id:"controlled_public_issue_intake_workflow_unknown",label:"Issue intake workflow unknown",phase,severity:"critical",reason:"Issue intake must be manual or explicitly controlled.",requiredAction:"Document the public feedback workflow."}:undefined,plan.feedbackCollectedAutomatically?{id:"controlled_public_issue_intake_feedback_auto_collected",label:"Feedback collected automatically",phase,severity:"critical",reason:"Issue intake must not collect feedback automatically.",requiredAction:"Remove automatic feedback collection."}:undefined,plan.issuesSentExternally?{id:"controlled_public_issue_intake_external_send",label:"Issue sent externally",phase,severity:"critical",reason:"Issues must not be sent externally by code.",requiredAction:"Keep issue intake local/manual."}:undefined,plan.databaseWritten?{id:"controlled_public_issue_intake_database_write",label:"Database write",phase,severity:"critical",reason:"Issue intake readiness must not write databases.",requiredAction:"Keep readiness in memory."}:undefined].filter(Boolean) as TeoyubeControlledPublicLaunchActivationBlocker[];}
export function getControlledPublicIssueIntakeWarnings():TeoyubeControlledPublicLaunchActivationWarning[]{return[{id:"controlled_public_issue_intake_manual_only",label:"Issue intake is manual or controlled",phase,severity:"medium",message:"This confirms readiness but collects no real feedback.",recommendedAction:"Use manual or explicitly controlled issue logs during public launch."}];}
export function validateControlledPublicIssueIntakeReadiness(plan:TeoyubeControlledPublicIssueIntakePlan){const blockers=getControlledPublicIssueIntakeBlockers(plan);return{valid:blockers.length===0,blockers,warnings:getControlledPublicIssueIntakeWarnings()};}
export function createControlledPublicIssueIntakeReport(plan:TeoyubeControlledPublicIssueIntakePlan=createControlledPublicIssueIntakePlan()){const validation=validateControlledPublicIssueIntakeReadiness(plan);return{valid:validation.valid,ready:validation.valid,plan,checklistCount:plan.checklist.length,blockers:validation.blockers,warnings:validation.warnings,manualOrExplicitlyControlled:true,noFeedbackCollectedAutomatically:true,noExternalSend:true,noDatabaseWrites:true,generatedAt:new Date().toISOString()};}
