import { createControlledPublicLaunchActivationReport } from "../controlled-public-launch-activation-checklist";
import { createControlledPublicOwnerApprovalRecord, createControlledPublicOwnerApprovalReport } from "../controlled-public-owner-approval";
import { createControlledPublicLaunchWindowPlan, createControlledPublicLaunchWindowReport } from "../controlled-public-launch-window";
import { createControlledPublicAccessReadinessPlan, createControlledPublicAccessReadinessReport } from "../controlled-public-access-readiness";
import { createControlledPublicCommunicationReadinessPlan, createControlledPublicCommunicationReadinessReport } from "../controlled-public-communication-readiness";
import { createControlledPublicServiceStatusReport } from "../controlled-public-service-status-confirmation";
import { createControlledPublicFirstHourReadinessPlan, createControlledPublicFirstHourReadinessReport } from "../controlled-public-first-hour-readiness";
import { createControlledPublicIssueIntakePlan, createControlledPublicIssueIntakeReport } from "../controlled-public-issue-intake-readiness";
import { createControlledPublicPauseRollbackPlan, createControlledPublicPauseRollbackReport } from "../controlled-public-pause-rollback-readiness";
import { createControlledPublicActivationPackage, createControlledPublicActivationPackageReport } from "../controlled-public-activation-package";
import { runControlledPublicLaunchActivationAudit } from "../controlled-public-launch-activation-audit";
export function runPublicLaunchExecution61Example(){const activation=createControlledPublicLaunchActivationReport();const owner=createControlledPublicOwnerApprovalReport(createControlledPublicOwnerApprovalRecord());const windowPlan=createControlledPublicLaunchWindowReport(createControlledPublicLaunchWindowPlan());const access=createControlledPublicAccessReadinessReport(createControlledPublicAccessReadinessPlan());const communication=createControlledPublicCommunicationReadinessReport(createControlledPublicCommunicationReadinessPlan());const services=createControlledPublicServiceStatusReport();const firstHour=createControlledPublicFirstHourReadinessReport(createControlledPublicFirstHourReadinessPlan());const issueIntake=createControlledPublicIssueIntakeReport(createControlledPublicIssueIntakePlan());const pauseRollback=createControlledPublicPauseRollbackReport(createControlledPublicPauseRollbackPlan());const activationPackage=createControlledPublicActivationPackageReport(createControlledPublicActivationPackage());const audit=runControlledPublicLaunchActivationAudit();return{activationDecision:activation.decision,ownerDecision:owner.decision,windowReady:windowPlan.ready,accessReady:access.ready,communicationReady:communication.ready,servicesReady:services.ready,firstHourReady:firstHour.ready,issueIntakeReady:issueIntake.ready,pauseRollbackReady:pauseRollback.ready,packageDecision:activationPackage.decision,auditComplete:audit.complete,nextStep:audit.nextStep,noPublicLaunchPerformed:true,noUsersContacted:true,noFeedbackCollectedAutomatically:true,noPublicUrlFetched:true,generatedAt:new Date().toISOString()};}
