import type { TeoyubeControlledPublicLaunchActivationDecision } from "../controlled-public-launch-activation-contracts";
import { createControlledPublicLaunchActivationReport } from "../controlled-public-launch-activation-checklist";
import { createControlledPublicOwnerApprovalChecklist } from "../controlled-public-owner-approval";
import { createControlledPublicLaunchWindowPlan, createControlledPublicLaunchWindowReport } from "../controlled-public-launch-window";
import { createControlledPublicAccessReadinessPlan, createControlledPublicAccessReadinessReport } from "../controlled-public-access-readiness";
import { createControlledPublicCommunicationReadinessPlan, createControlledPublicCommunicationReadinessReport } from "../controlled-public-communication-readiness";
import { createControlledPublicServiceStatusReport } from "../controlled-public-service-status-confirmation";
import { createControlledPublicFirstHourReadinessPlan, createControlledPublicFirstHourReadinessReport } from "../controlled-public-first-hour-readiness";
import { createControlledPublicIssueIntakePlan, createControlledPublicIssueIntakeReport } from "../controlled-public-issue-intake-readiness";
import { createControlledPublicPauseRollbackPlan, createControlledPublicPauseRollbackReport } from "../controlled-public-pause-rollback-readiness";
import { createControlledPublicActivationPackage, createControlledPublicActivationPackageReport } from "../controlled-public-activation-package";
import { runControlledPublicLaunchActivationAudit } from "../controlled-public-launch-activation-audit";
export function runPublicLaunchExecution61SmokeCheck(){const activation=createControlledPublicLaunchActivationReport();const decision:TeoyubeControlledPublicLaunchActivationDecision=activation.decision;const ownerChecklist=createControlledPublicOwnerApprovalChecklist();const windowPlan=createControlledPublicLaunchWindowPlan();const windowReport=createControlledPublicLaunchWindowReport(windowPlan);const accessPlan=createControlledPublicAccessReadinessPlan();const access=createControlledPublicAccessReadinessReport(accessPlan);const communication=createControlledPublicCommunicationReadinessReport(createControlledPublicCommunicationReadinessPlan());const services=createControlledPublicServiceStatusReport();const firstHourPlan=createControlledPublicFirstHourReadinessPlan();const firstHour=createControlledPublicFirstHourReadinessReport(firstHourPlan);const issueIntake=createControlledPublicIssueIntakeReport(createControlledPublicIssueIntakePlan());const pauseRollback=createControlledPublicPauseRollbackReport(createControlledPublicPauseRollbackPlan());const pkg=createControlledPublicActivationPackage();const pkgReport=createControlledPublicActivationPackageReport(pkg);const audit=runControlledPublicLaunchActivationAudit();const checks=[decision==="ready_for_manual_public_activation",activation.ready&&activation.checklistCount>=25,ownerChecklist.length>=15,windowReport.ready&&!windowPlan.scheduledByCode&&!windowPlan.calendarInvitesSent,access.ready&&!accessPlan.userContactFromCode,communication.ready&&communication.noMessagesSent,services.ready&&services.noExternalServicesCalled,firstHour.ready&&!firstHourPlan.fetchesPublicUrls,issueIntake.ready&&issueIntake.manualOrExplicitlyControlled,pauseRollback.ready&&pauseRollback.noRollbackPerformed,pkgReport.ready&&pkg.inMemoryOnly,audit.complete&&audit.completionPercentage===100,!pkg.publicLaunchPerformed&&!pkg.usersContacted&&!pkg.feedbackCollectedAutomatically&&!pkg.publicUrlFetched&&!pkg.databaseWritten&&!pkg.analyticsSent&&!pkg.externalServicesCalled];return{valid:checks.every(Boolean),checkCount:checks.length,passedCheckCount:checks.filter(Boolean).length,controlledPublicActivationDecision:decision,nextStep:audit.nextStep,noPublicLaunchPerformed:true,noUsersContacted:true,noFeedbackCollectedAutomatically:true,noPublicUrlFetched:true,noUnapprovedDatabaseExternalApisAnalyticsProviderServiceWorkerLocalStorageCookiesIndexedDbOrFileWritesRequired:true,audit,generatedAt:new Date().toISOString()};}
